<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Exception on Polarlights</title>
    <link>http://localhost:1313/tags/exception/</link>
    <description>Recent content in Exception on Polarlights</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en</language>
    <lastBuildDate>Mon, 16 Feb 2015 04:00:00 +0800</lastBuildDate>
    
	<atom:link href="http://localhost:1313/tags/exception/index.xml" rel="self" type="application/rss+xml" />
    
    
    <item>
      <title>再谈Ruby的异常处理(学习笔记)</title>
      <link>http://localhost:1313/post/let-us-talk-about-exception-again/</link>
      <pubDate>Mon, 16 Feb 2015 04:00:00 +0800</pubDate>
      
      <guid>http://localhost:1313/post/let-us-talk-about-exception-again/</guid>
      <description>Throw &amp;amp; Catchthrow和catch是Kernel中的方法，它们定义了一种可以从代码块中，穿过多次的代码级数，与catch一同定义的代码块退</description>
    </item>
    
  </channel>
</rss>